import React from "react";
import Head from 'next/head';
import Link from "next/link";
import NavBar from '../components/NavBar';
import PopulateDB from '../components/PopulateDB';
import styles from '../styles/Home.module.css';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>City Ranker</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz,wght@8..144,200&display=swap" rel="stylesheet" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NavBar />
      {/* <PopulateDB /> */}
      <main>
        <div className="relative flex items-center content-center justify-center pt-16 pb-32 h-100 min-h-screen-75">
          <div
            className="bg-[url('../img/turquoise2.jpeg')] absolute w-full h-full bg-center rounded-lg bg-cover md:top-20"
            // style={{
            //   backgroundImage:
            //     "url('../img/charleston.jpeg')",
            // }}
          >
            <span
              id="blackOverlay"
              className="absolute w-full h-full bg-black rounded-lg opacity-20"
            ></span>
          </div>
          <div className="container relative mx-auto md:top-20">
            <div className="flex flex-wrap items-center">
              <div className="w-full px-4 ml-auto mr-auto text-center lg:w-6/12">
                <div className="pr-12">
                  <h1 className="text-5xl font-semibold text-white">
                    Let us help you plan your next chapter.
                  </h1>
                  <h2 className="mt-4 text-xl text-white">
                    Life is hard. Deciding where to live it doesn't have to be.
                  </h2>
                </div>
              </div>
            </div>
          </div>
          <div
            className="absolute bottom-0 left-0 right-0 top-auto w-full h-16 overflow-hidden pointer-events-none"
            style={{ transform: "translateZ(0)" }}
          >
            <svg
              className="absolute bottom-0 overflow-hidden"
              xmlns="http://www.w3.org/2000/svg"
              preserveAspectRatio="none"
              version="1.1"
              viewBox="0 0 2560 100"
              x="0"
              y="0"
            >
              <polygon
                className="fill-current text-blueGray-200"
                points="2560 0 2560 100 0 100"
              ></polygon>
            </svg>
          </div>
        </div>

        <section className="relative pt-20 pb-6">
          <div
            className="absolute top-0 left-0 right-0 bottom-auto w-full h-20 -mt-20 overflow-hidden pointer-events-none"
            style={{ transform: "translateZ(0)" }}
          >
            <svg
              className="absolute bottom-0 overflow-hidden"
              xmlns="http://www.w3.org/2000/svg"
              preserveAspectRatio="none"
              version="1.1"
              viewBox="0 0 2560 100"
              x="0"
              y="0"
            >
              <polygon
                className="text-white fill-current"
                points="2560 0 2560 100 0 100"
              ></polygon>
            </svg>
          </div>

          <div className="bg-[url('../img/miltiadis-fragkidis-5ULk8EgE8tg-unsplash.jpg')] pb-14 rounded-lg mt-5 bg-no-repeat bg-cover">
          <div className="container px-2 pt-20 mx-auto">
            <div className="flex flex-wrap items-center">
              <div className="w-full px-4 ml-auto mr-auto md:w-4/12">
                <img
                  alt="A retro map of san diego in the shape of a heart"
                  className="w-full rounded-lg shadow-lg"
                  src="https://i.pinimg.com/564x/59/8f/ce/598fcea4d0c48c888a169cdfc65800b2.jpg"
                  // src="img/san-diego.heart.jpeg"
                />
              </div>
              <div className="w-full px-10 py-10 ml-auto mr-auto bg-orange-100 rounded-lg opacity-70 md:w-4/12">
                <div>
                  {/* <div className="inline-flex items-center justify-center w-16 h-16 p-3 mb-6 text-center rounded-full shadow-lg text-blueGray-500 bg-blueGray-200">
                    <i className="text-xl fas fa-rocket"></i>
                  </div>  */}
                  <h3 className="text-3xl font-semibold">CityRank's Inspiration</h3>
                  <p className="mt-4 text-lg leading-relaxed text-blueGray-500">
                    Covid changed the world. It changed the way we live and the way we work. This major disruption to our societies gave people a chance to reevaluate what they want and inject more intention into their lives and routines. Continuing to live somewhere that doesn't add to your happiness and propel you towards your goals is a choice, and it's one you don't have make.
                  </p>
                  <p className="mt-4 text-lg leading-relaxed text-blueGray-500">
                    CityRanker is here to provide the data and tools to allow you to make the choice of where to live your life with the care and intention it deserves.
                  </p>
                </div>
              </div>
            </div>
            
          </div>
          </div>
        </section>
        {/* testing out adding wrapper background imaage div */}
        <div className="bg-[url('../img/greg-rakozy-j5QK3ZDRa-s-unsplash.jpg')] pb-14 rounded-lg pt-14 bg-no-repeat bg-cover">
        <section className="pb-36">
          <div className="container px-4 mx-auto">
            
            <div className="flex flex-wrap mx-auto">
              <div className="w-full pr-24 mb-12 ml-auto md:w-6/12 lg:w-6/12 lg:mb-0">
                  {/* <div className="inline-flex items-center justify-center w-16 h-16 p-3 mb-6 text-center rounded-full shadow-lg text-blueGray-500 bg-blueGray-200">
                    <i className="text-xl fas fa-rocket"></i>
                  </div> */}
                  <h3 className="text-3xl font-semibold">An evolving application</h3>
                  <p className="mt-4 text-lg leading-relaxed text-blueGray-500">
                    CityRank is an actively growing application. Features currently available to CityRank users:
                  </p>
                  <ul className="mt-2 list-none">
                    <li className="py-1">
                      <div className="flex items-center">
                        <div>
                          <span className="inline-block px-2 py-1 mr-3 text-xs font-semibold uppercase rounded-full text-blueGray-500 bg-blueGray-100">
                            <p>⚫</p>
                          </span>
                        </div>
                        <div>
                          <h4 className="text-blueGray-500">
                          Automated search of dozens of cities based on a flexible variety of metrics such as city size, location, cost of living, ease of travel, etc.
                          </h4>
                        </div>
                      </div>
                    </li>
                    <li className="py-1">
                      <div className="flex items-center">
                        <div>
                          <span className="inline-block px-2 py-1 mr-3 text-xs font-semibold uppercase rounded-full text-blueGray-500 bg-blueGray-100">
                            <p>⚫</p>
                          </span>
                        </div>
                        <div>
                          <h4 className="text-blueGray-500">
                            Create user curated categories of cities such as "Close to family" or "Affordable"
                          </h4>
                        </div>
                      </div>
                    </li>
                    <li className="py-1">
                      <div className="flex items-center">
                        <div>
                          <span className="inline-block px-2 py-1 mr-3 text-xs font-semibold uppercase rounded-full text-blueGray-500 bg-blueGray-100">
                            <p>⚫</p>
                          </span>
                        </div>
                        <div>
                          <h4 className="text-blueGray-500">
                            Save and sort cities to their categories with notes to themselves
                          </h4>
                        </div>
                      </div>
                    </li>
                  </ul>
                  <p className="mt-4 text-lg leading-relaxed text-blueGray-500">Additional, in work features:</p>
                  <ul className="mt-2 list-none">
                    <li className="py-1">
                      <div className="flex items-center">
                        <div>
                          <span className="inline-block px-2 py-1 mr-3 text-xs font-semibold uppercase rounded-full text-blueGray-500 bg-blueGray-100">
                            <p>⚫</p>
                          </span>
                        </div>
                        <div>
                          <h4 className="text-blueGray-500">
                            Continuing to add cities to our data set
                          </h4>
                        </div>
                      </div>
                    </li>
                    <li className="py-1">
                      <div className="flex items-center">
                        <div>
                          <span className="inline-block px-2 py-1 mr-3 text-xs font-semibold uppercase rounded-full text-blueGray-500 bg-blueGray-100">
                            <p>⚫</p>
                          </span>
                        </div>
                        <div>
                          <h4 className="text-blueGray-500">
                            Adding additional filter options such as climate, safety, political orientation, average salary for your job title, etc.
                          </h4>
                        </div>
                      </div>
                    </li>
                    <li className="py-1">
                      <div className="flex items-center">
                        <div>
                          <span className="inline-block px-2 py-1 mr-3 text-xs font-semibold uppercase rounded-full text-blueGray-500 bg-blueGray-100">
                            <p>⚫</p>
                          </span>
                        </div>
                        <div>
                          <h4 className="text-blueGray-500">
                            Simple smart search, and advanced search options
                          </h4>
                        </div>
                      </div>
                    </li>
                    <li className="py-1">
                      <div className="flex items-center">
                        <div>
                          <span className="inline-block px-2 py-1 mr-3 text-xs font-semibold uppercase rounded-full text-blueGray-500 bg-blueGray-100">
                            <p>⚫</p>
                          </span>
                        </div>
                        <div>
                          <h4 className="text-blueGray-500">
                            Comparison of the cities you're interested in to the one you currently live in
                          </h4>
                        </div>
                      </div>
                    </li>
                    <li className="py-1">
                      <div className="flex items-center">
                        <div>
                          <span className="inline-block px-2 py-1 mr-3 text-xs font-semibold uppercase rounded-full text-blueGray-500 bg-blueGray-100">
                            <p>⚫</p>
                          </span>
                        </div>
                        <div>
                          <h4 className="text-blueGray-500">
                            Map view for saved cities
                          </h4>
                        </div>
                      </div>
                    </li>
                    <li className="py-1">
                      <div className="flex items-center">
                        <div>
                          <span className="inline-block px-2 py-1 mr-3 text-xs font-semibold uppercase rounded-full text-blueGray-500 bg-blueGray-100">
                            <p>⚫</p>
                          </span>
                        </div>
                        <div>
                          <h4 className="text-blueGray-500">
                          Eventual partnerships with companies hiring remote workers, or recruiters looking for candidates in specific cities
                          </h4>
                        </div>
                      </div>
                    </li>
                  </ul>
              </div>
              <div className="w-full pl-10 mb-12 mr-auto md:w-6/12 lg:w-3/12 center lg:mb-0">
                <div className="flex flex-wrap justify-center mb-12 text-center">
                  <div className="w-full px-6 lg:w-6/12">
                    <h2 className="text-4xl font-semibold">Our Team</h2>
                  </div>
                </div>
                <div className="px-6">
                  <img
                    alt="image of web developer for this website"
                    src="https://scontent-atl3-1.xx.fbcdn.net/v/t1.6435-9/182773670_10158259168526453_7629140523842622126_n.jpg?_nc_cat=101&ccb=1-6&_nc_sid=730e14&_nc_ohc=JeY6CvX7jr8AX_dtYvg&_nc_ht=scontent-atl3-1.xx&oh=00_AT-CFBmU5WSqCEVes8mrqvA_K7yteBQZmz3HHIRRNtwZpQ&oe=62A1A8A9"
                    className="mx-auto rounded-full shadow-lg max-w-120-px"
                  />
                  <div className="pt-6 text-center">
                    <h5 className="text-xl font-bold">Molly McDonough</h5>
                    <p className="mt-1 text-sm font-semibold uppercase text-blueGray-400">
                      Builder of all things, introducer of all bugs
                    </p>
                    {/* <div className="mt-6">
                      <button
                        className="w-8 h-8 mb-1 mr-1 text-white rounded-full outline-none bg-lightBlue-400 focus:outline-none"
                        type="button"
                      >
                        <i className="fab fa-twitter"></i>
                      </button>
                      <button
                        className="w-8 h-8 mb-1 mr-1 text-white rounded-full outline-none bg-lightBlue-600 focus:outline-none"
                        type="button"
                      >
                        <i className="fab fa-facebook-f"></i>
                      </button>
                      <button
                        className="w-8 h-8 mb-1 mr-1 text-white bg-pink-500 rounded-full outline-none focus:outline-none"
                        type="button"
                      >
                        <i className="fab fa-dribbble"></i>
                      </button>
                    </div> */}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="relative block pb-20 bg-blueGray-800">
          <div
            className="absolute top-0 left-0 right-0 bottom-auto w-full h-20 -mt-20 overflow-hidden pointer-events-none"
            style={{ transform: "translateZ(0)" }}
          >
            <svg
              className="absolute bottom-0 overflow-hidden"
              xmlns="http://www.w3.org/2000/svg"
              preserveAspectRatio="none"
              version="1.1"
              viewBox="0 0 2560 100"
              x="0"
              y="0"
            >
              <polygon
                className="fill-current text-blueGray-800"
                points="2560 0 2560 100 0 100"
              ></polygon>
            </svg>
          </div>

          <div className="container px-4 mx-auto lg:pt-24 lg:pb-64">
            <div className="flex flex-wrap justify-center text-center">
              <div className="w-full px-4 lg:w-6/12">
                {/* <h2 className="text-4xl font-semibold text-white">
                  Build something
                </h2>
                <p className="mt-4 mb-4 text-lg leading-relaxed text-blueGray-400">
                  Put the potentially record low maximum sea ice extent tihs
                  year down to low ice. According to the National Oceanic and
                  Atmospheric Administration, Ted, Scambos.
                </p> */}
              </div>
            </div>
            <div className="flex flex-wrap justify-center mt-12">
              <div className="w-full px-4 text-center lg:w-3/12">
                {/* <div className="inline-flex items-center justify-center w-12 h-12 p-3 bg-white rounded-full shadow-lg text-blueGray-800">
                  <i className="text-xl fas fa-medal"></i>
                </div>
                <h6 className="mt-5 text-xl font-semibold text-white">
                  Excelent Services
                </h6>
                <p className="mt-2 mb-4 text-blueGray-400">
                  Some quick example text to build on the card title and make up
                  the bulk of the card's content.
                </p> */}
              </div>
              <div className="w-full px-4 text-center lg:w-3/12">
                {/* <div className="inline-flex items-center justify-center w-12 h-12 p-3 bg-white rounded-full shadow-lg text-blueGray-800">
                  <i className="text-xl fas fa-poll"></i>
                </div>
                <h5 className="mt-5 text-xl font-semibold text-white">
                  Grow your market
                </h5>
                <p className="mt-2 mb-4 text-blueGray-400">
                  Some quick example text to build on the card title and make up
                  the bulk of the card's content.
                </p> */}
              </div>
              <div className="w-full px-4 text-center lg:w-3/12">
                {/* <div className="inline-flex items-center justify-center w-12 h-12 p-3 bg-white rounded-full shadow-lg text-blueGray-800">
                  <i className="text-xl fas fa-lightbulb"></i>
                </div>
                <h5 className="mt-5 text-xl font-semibold text-white">
                  Launch time
                </h5>
                <p className="mt-2 mb-4 text-blueGray-400">
                  Some quick example text to build on the card title and make up
                  the bulk of the card's content.
                </p> */}
              </div>
            </div>
          </div>
        </section>
        <section className="relative block py-24 lg:pt-0 bg-blueGray-800">
          <div className="container px-4 mx-auto">
            <div className="flex flex-wrap justify-center -mt-48 lg:-mt-64">
              <div className="w-full px-4 lg:w-6/12">
                <div className="relative flex flex-col w-full min-w-0 mb-6 break-words rounded-lg shadow-lg bg-blueGray-200">
                  <div className="flex-auto p-5 bg-orange-100 rounded-lg opacity-70 lg:p-10">
                    <h4 className="text-2xl font-semibold">
                      Questions or Concerns?
                    </h4>
                    <p className="mt-1 mb-4 leading-relaxed text-blueGray-500">
                      If you notice any issues with CityRanker's interface or data, or have any feature requests, please let us know.
                    </p>
                    <div className="relative w-full mt-8 mb-3">
                      <label
                        className="block mb-2 text-xs font-bold uppercase text-blueGray-600"
                        htmlFor="full-name"
                      >
                        Full Name
                      </label>
                      <input
                        type="text"
                        className="w-full px-3 py-3 text-sm transition-all duration-150 ease-linear bg-white border-0 rounded shadow placeholder-blueGray-300 text-blueGray-600 focus:outline-none focus:ring"
                        placeholder="Full Name"
                      />
                    </div>

                    <div className="relative w-full mb-3">
                      <label
                        className="block mb-2 text-xs font-bold uppercase text-blueGray-600"
                        htmlFor="email"
                      >
                        Email
                      </label>
                      <input
                        type="email"
                        className="w-full px-3 py-3 text-sm transition-all duration-150 ease-linear bg-white border-0 rounded shadow placeholder-blueGray-300 text-blueGray-600 focus:outline-none focus:ring"
                        placeholder="Email"
                      />
                    </div>

                    <div className="relative w-full mb-3">
                      <label
                        className="block mb-2 text-xs font-bold uppercase text-blueGray-600"
                        htmlFor="message"
                      >
                        Message
                      </label>
                      <textarea
                        rows="4"
                        cols="80"
                        className="w-full px-3 py-3 text-sm bg-white border-0 rounded shadow placeholder-blueGray-300 text-blueGray-600 focus:outline-none focus:ring"
                        placeholder="Type a message..."
                      />
                    </div>
                    <div className="mt-6 text-center">
                      <button
                        className="px-6 py-3 mb-1 mr-1 text-sm font-bold text-white uppercase transition-all duration-150 ease-linear rounded shadow outline-none bg-sky-600 bg-blueGray-800 active:bg-blueGray-600 hover:shadow-lg focus:outline-none"
                        type="button"
                      >
                        Send Message
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        </div>
      </main>
    </div>
  )
}

