import Head from 'next/head';
import Image from 'next/image';
import NavBar from '../components/NavBar';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>City Ranker</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NavBar />
      <h3>Gonna be a home page</h3>
    </div>
  )
}
